"""Add updated_at to roles

Revision ID: cfdb4a7d1eea
Revises: 
Create Date: 2025-11-03 13:48:04.109467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfdb4a7d1eea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dashboard_tabs', 'config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_dashboard_tabs_id'), 'dashboard_tabs', ['id'], unique=False)
    op.drop_constraint('dashboard_tabs_dashboard_id_fkey', 'dashboard_tabs', type_='foreignkey')
    op.create_foreign_key(None, 'dashboard_tabs', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dashboard_tabs', 'updated_at')
    op.drop_column('dashboard_tabs', 'created_at')
    op.alter_column('dashboards', 'layout',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('dashboards', 'created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.drop_constraint('dashboards_created_by_fkey', 'dashboards', type_='foreignkey')
    op.create_foreign_key(None, 'dashboards', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('dashboards', 'is_active')
    op.alter_column('data_models', 'schema_json',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('data_models_name_key', table_name='data_models')
    op.create_index(op.f('ix_data_models_id'), 'data_models', ['id'], unique=False)
    op.create_index(op.f('ix_data_models_name'), 'data_models', ['name'], unique=True)
    op.drop_column('data_models', 'display_name')
    op.drop_column('data_models', 'created_by')
    op.drop_column('data_models', 'description')
    op.drop_column('data_models', 'is_active')
    op.drop_column('data_models', 'table_name')
    op.alter_column('organizational_units', 'type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('COMPANY', 'DIVISION', 'DEPARTMENT', 'TEAM', name='orgunittype'),
               existing_nullable=False)
    op.alter_column('organizational_units', 'path',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_organizational_units_id'), 'organizational_units', ['id'], unique=False)
    op.drop_constraint('organizational_units_parent_id_fkey', 'organizational_units', type_='foreignkey')
    op.create_foreign_key(None, 'organizational_units', 'organizational_units', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('organizational_units', 'updated_at')
    op.drop_column('organizational_units', 'description')
    op.drop_index('permissions_action_idx', table_name='permissions')
    op.drop_index('permissions_resource_idx', table_name='permissions')
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.drop_column('permissions', 'created_at')
    op.drop_index('roles_name_key', table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('users', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'INACTIVE', name='userstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index('users_email_key', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'reset_token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_expires', mysql.DATETIME(fsp=3), nullable=True))
    op.add_column('users', sa.Column('email_verified', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('reset_token', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login', mysql.DATETIME(fsp=3), nullable=True))
    op.add_column('users', sa.Column('verification_token', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('users_email_key', 'users', ['email'], unique=True)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'INACTIVE', name='userstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index('roles_name_key', 'roles', ['name'], unique=True)
    op.add_column('permissions', sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False))
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.create_index('permissions_resource_idx', 'permissions', ['resource'], unique=False)
    op.create_index('permissions_action_idx', 'permissions', ['action'], unique=False)
    op.add_column('organizational_units', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('organizational_units', sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False))
    op.drop_constraint(None, 'organizational_units', type_='foreignkey')
    op.create_foreign_key('organizational_units_parent_id_fkey', 'organizational_units', 'organizational_units', ['parent_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_organizational_units_id'), table_name='organizational_units')
    op.alter_column('organizational_units', 'path',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('organizational_units', 'type',
               existing_type=sa.Enum('COMPANY', 'DIVISION', 'DEPARTMENT', 'TEAM', name='orgunittype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('data_models', sa.Column('table_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('data_models', sa.Column('is_active', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('data_models', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('data_models', sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('data_models', sa.Column('display_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_data_models_name'), table_name='data_models')
    op.drop_index(op.f('ix_data_models_id'), table_name='data_models')
    op.create_index('data_models_name_key', 'data_models', ['name'], unique=True)
    op.alter_column('data_models', 'schema_json',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False)
    op.add_column('dashboards', sa.Column('is_active', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.create_foreign_key('dashboards_created_by_fkey', 'dashboards', 'users', ['created_by'], ['id'], onupdate='CASCADE')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.alter_column('dashboards', 'created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('dashboards', 'layout',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.add_column('dashboard_tabs', sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False))
    op.add_column('dashboard_tabs', sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False))
    op.drop_constraint(None, 'dashboard_tabs', type_='foreignkey')
    op.create_foreign_key('dashboard_tabs_dashboard_id_fkey', 'dashboard_tabs', 'dashboards', ['dashboard_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_dashboard_tabs_id'), table_name='dashboard_tabs')
    op.alter_column('dashboard_tabs', 'config',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    # ### end Alembic commands ###
